hologin/urls.py
from django.urls import path
from . import views

app_name = 'hologin'

urlpatterns = [
    path('', views.index, name='index'),
    path('welcome', views.afterlogin, name='afterlogin'),
    path('signup', views.signup, name='signup'),
    path('logout',views.logout,name='logout'),
]

story_9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hologin.urls')),
]

hologin/models.py
from django.db import models

# Create your models here.

hologin/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import json
import requests
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import logout as django_logout


# Create your views here.
def index(request):
    if request.method == 'GET':
        return render(request, 'index.html')
    else:

        username = request.POST.get("username")
        password = request.POST.get("password")
        # fullname = request.POST.get("fullname")
        user = authenticate(username = username, password = password)
        if(user is not None):
            login(request,user)
            return redirect('hologin:afterlogin')

        messages.error(request,"Wrong password or username!!")
        return render(request, 'index.html')

def signup(request):

    if(request.method == 'GET'):
        return render(request, 'signup.html')
        
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")
        # fullname = request.POST.get("fullname")
        try:
            user = User.objects.get(username = username)
            messages.error(request,"Username taken, try again!!")
            return render(request,'signup.html')
        except:
            user = User.objects.create_user(username = username, password = password)
            messages.success(request,"Sign up successfull!")

            
            return redirect(reverse('hologin:index'))


@login_required(login_url = 'hologin:index')
def afterlogin(request):
    if request.method == 'GET':
        return render(request,'afterlogin.html')

def logout(request):
    django_logout(request)
    return redirect('hologin:index')

hologin/templates/afterlogin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Daijoubu?</title>
</head>
<style>
    body {
        background-image: url('/static/story7.jpg');
  }
</style>
<body>

    
    <body>
        <!-- Main Content -->
        <div class="container-fluid">
            <div class="row main-content bg-success text-center">
                <div class="col-md-4 text-center company__info">
                    <span class="company__logo"><h2><span class="fa fa-android"></span></h2></span>
                    <h3 class="company_title" style="margin-bottom: 15px;"><b>Hello,</b></h3>
                    <h3 class="company_title"><P>{{ user.username }}</P></h3>
                </div>
                <div class="col-md-8 col-xs-12 col-sm-12 login_form ">
                    <div class="container-fluid">
                        <div class="row">
                            
                        </div>
                        <div class="row">
                            <img src="https://media.giphy.com/media/LTFbyWuELIlqlXGLeZ/giphy.gif" style="width: 100%; margin-top: 25px;">
                            <div class="row">
                                <a href="{% url 'hologin:logout' %}">
                                <input type="submit" value="Log Out" class="btn">
                                </a>
                            </div>
                        </div>
                
                    </div>
                </div>
            </div>
        </div>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
    
</body>
</html>

hologin/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Daijoubu?</title>
</head>
<style>
    body {
        background-image: url('/static/story7.jpg');
  }
</style>
<body>

    
    <body>
        <!-- Main Content -->
        <div class="container-fluid">
            <div class="row main-content bg-success text-center">
                <div class="col-md-4 text-center company__info">
                    <span class="company__logo"><h2><span class="fa fa-android"></span></h2></span>
                    <h3 class="company_title" style="margin-bottom: 20px;"><b>Story 9</b></h3>
                    <h3 class="company_title"><P>Last but not least</P></h3>
                </div>
                <div class="col-md-8 col-xs-12 col-sm-12 login_form ">
                    <div class="container-fluid">
                        <div class="row justify-content-center">
                            <h2 style="margin-top: 30px;">LOG IN</h2>
                        </div>
                        <div class="row justify-content-center">
                            <form method="POST" class="form-group">
                                {% csrf_token %}
                                <div class="row">
                                    <input type="text" name="username" id="username" class="form__input" placeholder="Username" required>
                                </div>
                                <div class="row">
                                    <!-- <span class="fa fa-lock"></span> -->
                                    <input type="password" name="password" id="password" class="form__input" placeholder="Password" required>
                                </div>
                                <div class="row">
                                    <input type="submit" value="Submit" class="btn">
                                </div>
                            </form>
                        </div>
                        <div class="row justify-content-center">
                            <p>Don't have an account? <a href="{% url 'hologin:signup' %}">Register Here</a></p>
                        </div>
                        {% for i in messages %}
                        <h6 style="color: rgb(213, 95, 95);">{{ i }}</h6>
                        {% endfor %}
            
                    </div>
                </div>
            </div>
        </div>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
    
</body>
</html>

hologin/templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Daijoubu?</title>
</head>
<style>
    body {
        background-image: url('/static/story7.jpg');
  }
</style>
<body>

    
    <body>
        <!-- Main Content -->
        <div class="container-fluid">
            <div class="row main-content bg-success text-center">
                <div class="col-md-4 text-center company__info">
                    <span class="company__logo"><h2><span class="fa fa-android"></span></h2></span>
                    <h3 class="company_title" style="margin-bottom: 20px;"><b>Story 9</b></h3>
                    <h3 class="company_title"><P>Last but not least</P></h3>
                </div>
                <div class="col-md-8 col-xs-12 col-sm-12 login_form ">
                    <div class="container-fluid">
                        <div class="row justify-content-center"">
                            <h2 style="margin-top: 30px;">SIGN UP</h2>
                        </div>
                        <div class="row justify-content-center">
                            <form method="POST" class="form-group">
                                {% csrf_token %}
                                <div class="row">
                                    <input type="text" name="fullname" id="fullname" class="form__input" placeholder="Full Name" required>
                                </div>
                                <div class="row">
                                    <input type="text" name="username" id="username" class="form__input" placeholder="Username" required>
                                </div>
                                <div class="row">
                                    <!-- <span class="fa fa-lock"></span> -->
                                    <input type="password" name="password" id="password" class="form__input" placeholder="Password" required>
                                </div>
                                <div class="row">
                                    <input type="submit" value="Submit" class="btn">
                                </div>
                            </form>
                        </div>
                        {% for i in messages %}
                        <h6 style="color: rgb(223, 70, 70);">{{ i }}</h6>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </body>
    
</body>
</html>